// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisMortuorio.Data;

#nullable disable

namespace SisMortuorio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105051057_Refactor_StateMachine_EstadoComoString")]
    partial class Refactor_StateMachine_EstadoComoString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("FechaHora");

                    b.HasIndex("UsuarioID");

                    b.HasIndex("Modulo", "Accion");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.AutoridadExterna", b =>
                {
                    b.Property<int>("AutoridadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoridadID"));

                    b.Property<string>("CodigoEspecial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PlacaVehiculo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoAutoridad")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioRegistroID")
                        .HasColumnType("int");

                    b.HasKey("AutoridadID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("UsuarioRegistroID");

                    b.ToTable("AutoridadesExternas");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.CustodiaTransferencia", b =>
                {
                    b.Property<int>("TransferenciaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferenciaID"));

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraTransferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UbicacionDestino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UbicacionOrigen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioDestinoID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioOrigenID")
                        .HasColumnType("int");

                    b.HasKey("TransferenciaID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("UsuarioDestinoID");

                    b.HasIndex("UsuarioOrigenID");

                    b.ToTable("CustodiaTransferencias");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DeudaEconomica", b =>
                {
                    b.Property<int>("DeudaEconomicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeudaEconomicaID"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoDeuda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NumeroBoleta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObservacionesExoneracion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("PorcentajeExoneracion")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("UsuarioActualizacionID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioRegistroID")
                        .HasColumnType("int");

                    b.HasKey("DeudaEconomicaID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("UsuarioActualizacionID");

                    b.HasIndex("UsuarioRegistroID");

                    b.ToTable("DeudasEconomicas");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DeudaSangre", b =>
                {
                    b.Property<int>("DeudaSangreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeudaSangreID"));

                    b.Property<bool>("CompromisoFirmado")
                        .HasColumnType("bit");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TieneDeuda")
                        .HasColumnType("bit");

                    b.Property<int?>("UsuarioActualizacionID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioRegistroID")
                        .HasColumnType("int");

                    b.HasKey("DeudaSangreID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("UsuarioActualizacionID");

                    b.HasIndex("UsuarioRegistroID");

                    b.ToTable("DeudasSangre");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DocumentoLegal", b =>
                {
                    b.Property<int>("DocumentoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentoID"));

                    b.Property<bool>("EstaCompleto")
                        .HasColumnType("bit");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAdjunto")
                        .HasColumnType("datetime2");

                    b.Property<string>("RutaArchivo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioAdjuntoID")
                        .HasColumnType("int");

                    b.HasKey("DocumentoID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("UsuarioAdjuntoID");

                    b.ToTable("DocumentosLegales");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Expediente", b =>
                {
                    b.Property<int>("ExpedienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpedienteID"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoExpediente")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoQR")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiagnosticoFinal")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaGeneracionQR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraFallecimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("HC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MedicoCMP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MedicoCertificaNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MedicoRNE")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MotivoEliminacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroCama")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NumeroCertificadoSINADEF")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ServicioFallecimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("TipoExpediente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoSeguro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioCreadorID")
                        .HasColumnType("int");

                    b.HasKey("ExpedienteID");

                    b.HasIndex("CodigoExpediente")
                        .IsUnique();

                    b.HasIndex("CodigoQR")
                        .IsUnique()
                        .HasFilter("[CodigoQR] IS NOT NULL");

                    b.HasIndex("HC");

                    b.HasIndex("NumeroCertificadoSINADEF")
                        .IsUnique()
                        .HasFilter("[NumeroCertificadoSINADEF] IS NOT NULL");

                    b.HasIndex("NumeroDocumento");

                    b.HasIndex("UsuarioCreadorID");

                    b.ToTable("Expedientes");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.OcupacionBandeja", b =>
                {
                    b.Property<int>("OcupacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OcupacionID"));

                    b.Property<string>("BandejaID")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioAsignadorID")
                        .HasColumnType("int");

                    b.HasKey("OcupacionID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("UsuarioAsignadorID");

                    b.HasIndex("BandejaID", "FechaHoraSalida");

                    b.ToTable("OcupacionesBandejas");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Pertenencia", b =>
                {
                    b.Property<int>("PertenenciaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PertenenciaID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("PertenenciaID");

                    b.HasIndex("ExpedienteID");

                    b.ToTable("Pertenencias");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("NumeroDocumento");

                    b.HasIndex("RolID");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.AutoridadExterna", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.CustodiaTransferencia", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany("CustodiaTransferencias")
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("UsuarioDestinoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioOrigen")
                        .WithMany()
                        .HasForeignKey("UsuarioOrigenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioDestino");

                    b.Navigation("UsuarioOrigen");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DeudaEconomica", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DeudaSangre", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DocumentoLegal", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioAdjunto")
                        .WithMany()
                        .HasForeignKey("UsuarioAdjuntoID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioAdjunto");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Expediente", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.OcupacionBandeja", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioAsignador")
                        .WithMany()
                        .HasForeignKey("UsuarioAsignadorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioAsignador");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Pertenencia", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany("Pertenencias")
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Usuario", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Expediente", b =>
                {
                    b.Navigation("CustodiaTransferencias");

                    b.Navigation("Pertenencias");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
