// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisMortuorio.Data;

#nullable disable

namespace SisMortuorio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.ActaRetiro", b =>
                {
                    b.Property<int>("ActaRetiroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActaRetiroID"));

                    b.Property<string>("AutoridadApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AutoridadApellidoPaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AutoridadCargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AutoridadInstitucion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("AutoridadNombreCompleto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AutoridadNombres")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AutoridadNumeroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AutoridadPlacaVehiculo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AutoridadTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("AutoridadTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("DatosAdicionales")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Destino")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EstadoActa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<int?>("ExpedienteID1")
                        .HasColumnType("int");

                    b.Property<string>("FamiliarApellidoMaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FamiliarApellidoPaterno")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FamiliarNombreCompleto")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FamiliarNombres")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FamiliarNumeroDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FamiliarParentesco")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FamiliarTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("FamiliarTipoDocumento")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFirmaAdmisionista")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFirmaResponsable")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraFallecimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaSubidaPDF")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSupervisorVigilancia")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FirmadoAdmisionista")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("FirmadoResponsable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("FirmadoSupervisorVigilancia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("HistoriaClinica")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("JefeGuardiaCMP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("JefeGuardiaNombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MedicoCMP")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MedicoCertificaNombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("MedicoRNE")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreArchivoPDFFirmado")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreArchivoPDFSinFirmar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreCompletoFallecido")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NumeroCertificadoDefuncion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroDocumentoFallecido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroOficioLegal")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RutaPDFFirmado")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RutaPDFSinFirmar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ServicioFallecimiento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("TamañoPDFFirmado")
                        .HasColumnType("bigint");

                    b.Property<long?>("TamañoPDFSinFirmar")
                        .HasColumnType("bigint");

                    b.Property<int?>("TipoAutoridad")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentoFallecido")
                        .HasColumnType("int");

                    b.Property<int>("TipoSalida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("UsuarioAdmisionID")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioSubidaPDFID")
                        .HasColumnType("int");

                    b.HasKey("ActaRetiroID");

                    b.HasIndex("AutoridadNumeroDocumento");

                    b.HasIndex("ExpedienteID")
                        .IsUnique();

                    b.HasIndex("ExpedienteID1")
                        .IsUnique()
                        .HasFilter("[ExpedienteID1] IS NOT NULL");

                    b.HasIndex("FamiliarNumeroDocumento");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("NumeroCertificadoDefuncion");

                    b.HasIndex("NumeroOficioLegal");

                    b.HasIndex("TipoAutoridad");

                    b.HasIndex("TipoSalida");

                    b.HasIndex("UsuarioAdmisionID");

                    b.HasIndex("UsuarioSubidaPDFID");

                    b.HasIndex("TipoSalida", "FechaRegistro");

                    b.ToTable("ActasRetiro", (string)null);
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("IPOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("FechaHora");

                    b.HasIndex("UsuarioID");

                    b.HasIndex("Modulo", "Accion");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.AutoridadExterna", b =>
                {
                    b.Property<int>("AutoridadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AutoridadID"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoEspecial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("DocumentoEntregado")
                        .HasColumnType("bit");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<int?>("ExpedienteID1")
                        .HasColumnType("int");

                    b.Property<int?>("ExpedienteLegalID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaDocumentoOficial")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraLlegada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroDocumentoOficial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PlacaVehiculo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TipoAutoridad")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumento")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<int>("UsuarioRegistroID")
                        .HasColumnType("int");

                    b.HasKey("AutoridadID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("ExpedienteID1");

                    b.HasIndex("ExpedienteLegalID");

                    b.HasIndex("FechaHoraLlegada");

                    b.HasIndex("NumeroDocumento");

                    b.HasIndex("TipoAutoridad");

                    b.HasIndex("UsuarioRegistroID");

                    b.ToTable("AutoridadesExternas", (string)null);
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Bandeja", b =>
                {
                    b.Property<int>("BandejaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BandejaID"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraLiberacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoEliminacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UsuarioAsignaID")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioLiberaID")
                        .HasColumnType("int");

                    b.HasKey("BandejaID");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("UsuarioAsignaID");

                    b.HasIndex("UsuarioLiberaID");

                    b.ToTable("Bandejas");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.BandejaHistorial", b =>
                {
                    b.Property<int>("OcupacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OcupacionID"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("BandejaID")
                        .HasColumnType("int");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("UsuarioAsignadorID")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioLiberaID")
                        .HasColumnType("int");

                    b.HasKey("OcupacionID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("UsuarioAsignadorID");

                    b.HasIndex("UsuarioLiberaID");

                    b.HasIndex("BandejaID", "FechaHoraSalida");

                    b.ToTable("BandejaHistoriales");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.CustodiaTransferencia", b =>
                {
                    b.Property<int>("TransferenciaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransferenciaID"));

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraTransferencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("UbicacionDestino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UbicacionOrigen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioDestinoID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioOrigenID")
                        .HasColumnType("int");

                    b.HasKey("TransferenciaID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("UsuarioDestinoID");

                    b.HasIndex("UsuarioOrigenID");

                    b.ToTable("CustodiaTransferencias");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DeudaEconomica", b =>
                {
                    b.Property<int>("DeudaEconomicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeudaEconomicaID"));

                    b.Property<int?>("AsistentaSocialID")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaExoneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoDeuda")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MontoExonerado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NombreArchivoSustento")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NumeroBoleta")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroBoletaExoneracion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ObservacionesExoneracion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ObservacionesPago")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RutaPDFSustento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long?>("TamañoArchivoSustento")
                        .HasColumnType("bigint");

                    b.Property<string>("TipoExoneracion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("UsuarioActualizacionID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioRegistroID")
                        .HasColumnType("int");

                    b.HasKey("DeudaEconomicaID");

                    b.HasIndex("AsistentaSocialID");

                    b.HasIndex("ExpedienteID")
                        .IsUnique();

                    b.HasIndex("UsuarioActualizacionID");

                    b.HasIndex("UsuarioRegistroID");

                    b.ToTable("DeudasEconomicas");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DeudaSangre", b =>
                {
                    b.Property<int>("DeudaSangreID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeudaSangreID"));

                    b.Property<bool>("AnuladaPorMedico")
                        .HasColumnType("bit");

                    b.Property<int?>("CantidadUnidades")
                        .HasColumnType("int");

                    b.Property<string>("DNIFamiliarCompromiso")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Detalle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCompromisoFirmado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("JustificacionAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MedicoAnulaID")
                        .HasColumnType("int");

                    b.Property<string>("NombreFamiliarCompromiso")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RutaPDFCompromiso")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoSangre")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("UsuarioActualizacionID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioRegistroID")
                        .HasColumnType("int");

                    b.HasKey("DeudaSangreID");

                    b.HasIndex("ExpedienteID")
                        .IsUnique();

                    b.HasIndex("MedicoAnulaID");

                    b.HasIndex("UsuarioActualizacionID");

                    b.HasIndex("UsuarioRegistroID");

                    b.ToTable("DeudasSangre");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DocumentoExpediente", b =>
                {
                    b.Property<int>("DocumentoExpedienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentoExpedienteID"));

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<string>("ExtensionArchivo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("FechaHoraSubida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaHoraVerificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TamañoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioSubioID")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioVerificoID")
                        .HasColumnType("int");

                    b.HasKey("DocumentoExpedienteID");

                    b.HasIndex("Estado");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("FechaHoraSubida");

                    b.HasIndex("TipoDocumento");

                    b.HasIndex("UsuarioSubioID");

                    b.HasIndex("UsuarioVerificoID");

                    b.HasIndex("ExpedienteID", "TipoDocumento");

                    b.ToTable("DocumentosExpediente");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DocumentoLegal", b =>
                {
                    b.Property<int>("DocumentoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentoID"));

                    b.Property<bool>("Adjuntado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<int?>("ExpedienteID1")
                        .HasColumnType("int");

                    b.Property<int?>("ExpedienteLegalID")
                        .HasColumnType("int");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("FechaAdjunto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaValidacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ObservacionesValidacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TamañoArchivo")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoDocumento")
                        .HasMaxLength(30)
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioAdjuntoID")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioValidadorID")
                        .HasColumnType("int");

                    b.Property<bool>("Validado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("DocumentoID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("ExpedienteID1");

                    b.HasIndex("ExpedienteLegalID");

                    b.HasIndex("FechaAdjunto");

                    b.HasIndex("TipoDocumento");

                    b.HasIndex("UsuarioAdjuntoID");

                    b.HasIndex("UsuarioValidadorID");

                    b.ToTable("DocumentosLegales", (string)null);
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Expediente", b =>
                {
                    b.Property<int>("ExpedienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpedienteID"));

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BandejaActualID")
                        .HasColumnType("int");

                    b.Property<string>("CodigoExpediente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoQR")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DiagnosticoFinal")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DocumentacionCompleta")
                        .HasColumnType("bit");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("bit");

                    b.Property<string>("EstadoActual")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaGeneracionQR")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraFallecimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaValidacionAdmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("HC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MedicoCMP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MedicoCertificaNombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MedicoExternoCMP")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MedicoExternoNombre")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MedicoRNE")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MotivoEliminacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroCama")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NumeroCertificadoSINADEF")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("RequiereIntervencionLegal")
                        .HasColumnType("bit");

                    b.Property<string>("ServicioFallecimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoExpediente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TipoSalidaPreliminar")
                        .HasColumnType("int");

                    b.Property<string>("TipoSeguro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UsuarioAdmisionID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreadorID")
                        .HasColumnType("int");

                    b.HasKey("ExpedienteID");

                    b.HasIndex("BandejaActualID");

                    b.HasIndex("CodigoExpediente")
                        .IsUnique();

                    b.HasIndex("CodigoQR")
                        .IsUnique()
                        .HasFilter("[CodigoQR] IS NOT NULL");

                    b.HasIndex("HC");

                    b.HasIndex("NumeroCertificadoSINADEF")
                        .IsUnique()
                        .HasFilter("[NumeroCertificadoSINADEF] IS NOT NULL");

                    b.HasIndex("NumeroDocumento");

                    b.HasIndex("UsuarioAdmisionID");

                    b.HasIndex("UsuarioCreadorID");

                    b.ToTable("Expedientes");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.ExpedienteLegal", b =>
                {
                    b.Property<int>("ExpedienteLegalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpedienteLegalID"));

                    b.Property<bool>("AutorizadoJefeGuardia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Comisaria")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Destino")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<int?>("ExpedienteID1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaValidacionAdmision")
                        .HasColumnType("datetime2");

                    b.Property<string>("Fiscalia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("JefeGuardiaID")
                        .HasColumnType("int");

                    b.Property<string>("NumeroOficioPNP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ObservacionesAdmision")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ObservacionesJefeGuardia")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("UsuarioActualizacionID")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioAdmisionID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioRegistroID")
                        .HasColumnType("int");

                    b.Property<bool>("ValidadoAdmision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ExpedienteLegalID");

                    b.HasIndex("Estado");

                    b.HasIndex("ExpedienteID")
                        .IsUnique();

                    b.HasIndex("ExpedienteID1")
                        .IsUnique()
                        .HasFilter("[ExpedienteID1] IS NOT NULL");

                    b.HasIndex("FechaCreacion");

                    b.HasIndex("JefeGuardiaID");

                    b.HasIndex("UsuarioActualizacionID");

                    b.HasIndex("UsuarioAdmisionID");

                    b.HasIndex("UsuarioRegistroID");

                    b.ToTable("ExpedientesLegales", (string)null);
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Pertenencia", b =>
                {
                    b.Property<int>("PertenenciaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PertenenciaID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("PertenenciaID");

                    b.HasIndex("ExpedienteID");

                    b.ToTable("Pertenencias");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.SalidaMortuorio", b =>
                {
                    b.Property<int>("SalidaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalidaID"));

                    b.Property<int>("ActaRetiroID")
                        .HasColumnType("int");

                    b.Property<string>("AyudanteFuneraria")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("BandejaLiberadaID")
                        .HasColumnType("int");

                    b.Property<string>("ConductorFuneraria")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DNIAyudante")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DNIConductor")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Destino")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DetalleIncidente")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<int?>("ExpedienteID1")
                        .HasColumnType("int");

                    b.Property<int?>("ExpedienteLegalID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraSalida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FunerariaRUC")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("FunerariaTelefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IncidenteRegistrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NombreFuneraria")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PlacaVehiculo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RegistradoPorID")
                        .HasColumnType("int");

                    b.Property<int?>("TiempoPermanenciaMinutos")
                        .HasColumnType("int");

                    b.HasKey("SalidaID");

                    b.HasIndex("ActaRetiroID")
                        .IsUnique();

                    b.HasIndex("BandejaLiberadaID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("ExpedienteID1")
                        .IsUnique()
                        .HasFilter("[ExpedienteID1] IS NOT NULL");

                    b.HasIndex("ExpedienteLegalID");

                    b.HasIndex("FechaHoraSalida");

                    b.HasIndex("RegistradoPorID");

                    b.ToTable("SalidasMortuorio", (string)null);
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.SolicitudCorreccionExpediente", b =>
                {
                    b.Property<int>("SolicitudID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudID"));

                    b.Property<bool>("BrazaleteReimpreso")
                        .HasColumnType("bit");

                    b.Property<string>("DatosIncorrectos")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("DescripcionProblema")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescripcionResolucion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaHoraNotificacionJefeGuardia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraNotificacionSupervisora")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraReimpresion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NotificadoJefeGuardia")
                        .HasColumnType("bit");

                    b.Property<bool>("NotificadoSupervisora")
                        .HasColumnType("bit");

                    b.Property<string>("ObservacionesResolucion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ObservacionesSolicitud")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Resuelta")
                        .HasColumnType("bit");

                    b.Property<int>("UsuarioResponsableID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioSolicitaID")
                        .HasColumnType("int");

                    b.HasKey("SolicitudID");

                    b.HasIndex("ExpedienteID");

                    b.HasIndex("FechaHoraSolicitud");

                    b.HasIndex("Resuelta");

                    b.HasIndex("UsuarioResponsableID");

                    b.HasIndex("UsuarioSolicitaID");

                    b.HasIndex("Resuelta", "FechaHoraSolicitud");

                    b.ToTable("SolicitudesCorreccion");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoDocumento")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("NumeroDocumento");

                    b.HasIndex("RolID");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.VerificacionMortuorio", b =>
                {
                    b.Property<int>("VerificacionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerificacionID"));

                    b.Property<bool>("Aprobada")
                        .HasColumnType("bit");

                    b.Property<int?>("BandejaAsignadaID")
                        .HasColumnType("int");

                    b.Property<string>("CodigoExpedienteBrazalete")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("CodigoExpedienteCoincide")
                        .HasColumnType("bit");

                    b.Property<bool>("DocumentoCoincide")
                        .HasColumnType("bit");

                    b.Property<int>("ExpedienteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraVerificacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("HCBrazalete")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("HCCoincide")
                        .HasColumnType("bit");

                    b.Property<string>("MotivoRechazo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("NombreCoincide")
                        .HasColumnType("bit");

                    b.Property<string>("NombreCompletoBrazalete")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NumeroDocumentoBrazalete")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ServicioBrazalete")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ServicioCoincide")
                        .HasColumnType("bit");

                    b.Property<int>("TecnicoAmbulanciaID")
                        .HasColumnType("int");

                    b.Property<string>("TipoDocumentoBrazalete")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VigilanteID")
                        .HasColumnType("int");

                    b.HasKey("VerificacionID");

                    b.HasIndex("BandejaAsignadaID");

                    b.HasIndex("ExpedienteID")
                        .IsUnique();

                    b.HasIndex("FechaHoraVerificacion");

                    b.HasIndex("TecnicoAmbulanciaID");

                    b.HasIndex("VigilanteID");

                    b.HasIndex("ExpedienteID", "Aprobada");

                    b.ToTable("VerificacionesMortuorio");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Rol", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.ActaRetiro", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithOne()
                        .HasForeignKey("SisMortuorio.Data.Entities.ActaRetiro", "ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Expediente", null)
                        .WithOne("ActaRetiro")
                        .HasForeignKey("SisMortuorio.Data.Entities.ActaRetiro", "ExpedienteID1");

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioAdmision")
                        .WithMany()
                        .HasForeignKey("UsuarioAdmisionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioSubidaPDF")
                        .WithMany()
                        .HasForeignKey("UsuarioSubidaPDFID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioAdmision");

                    b.Navigation("UsuarioSubidaPDF");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.AuditLog", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.AutoridadExterna", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Expediente", null)
                        .WithMany("AutoridadesExternas")
                        .HasForeignKey("ExpedienteID1");

                    b.HasOne("SisMortuorio.Data.Entities.ExpedienteLegal", "ExpedienteLegal")
                        .WithMany("Autoridades")
                        .HasForeignKey("ExpedienteLegalID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("ExpedienteLegal");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Bandeja", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioAsigna")
                        .WithMany()
                        .HasForeignKey("UsuarioAsignaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioLibera")
                        .WithMany()
                        .HasForeignKey("UsuarioLiberaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioAsigna");

                    b.Navigation("UsuarioLibera");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.BandejaHistorial", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Bandeja", "Bandeja")
                        .WithMany("Historial")
                        .HasForeignKey("BandejaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany("HistorialBandejas")
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioAsignador")
                        .WithMany()
                        .HasForeignKey("UsuarioAsignadorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioLibera")
                        .WithMany()
                        .HasForeignKey("UsuarioLiberaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bandeja");

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioAsignador");

                    b.Navigation("UsuarioLibera");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.CustodiaTransferencia", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany("CustodiaTransferencias")
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioDestino")
                        .WithMany()
                        .HasForeignKey("UsuarioDestinoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioOrigen")
                        .WithMany()
                        .HasForeignKey("UsuarioOrigenID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioDestino");

                    b.Navigation("UsuarioOrigen");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DeudaEconomica", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "AsistentaSocial")
                        .WithMany()
                        .HasForeignKey("AsistentaSocialID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithOne("DeudaEconomica")
                        .HasForeignKey("SisMortuorio.Data.Entities.DeudaEconomica", "ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsistentaSocial");

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DeudaSangre", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithOne("DeudaSangre")
                        .HasForeignKey("SisMortuorio.Data.Entities.DeudaSangre", "ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "MedicoAnula")
                        .WithMany()
                        .HasForeignKey("MedicoAnulaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("MedicoAnula");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DocumentoExpediente", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany("Documentos")
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioSubio")
                        .WithMany()
                        .HasForeignKey("UsuarioSubioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioVerifico")
                        .WithMany()
                        .HasForeignKey("UsuarioVerificoID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioSubio");

                    b.Navigation("UsuarioVerifico");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.DocumentoLegal", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Expediente", null)
                        .WithMany("DocumentosLegales")
                        .HasForeignKey("ExpedienteID1");

                    b.HasOne("SisMortuorio.Data.Entities.ExpedienteLegal", "ExpedienteLegal")
                        .WithMany("Documentos")
                        .HasForeignKey("ExpedienteLegalID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioAdjunto")
                        .WithMany()
                        .HasForeignKey("UsuarioAdjuntoID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioValidador")
                        .WithMany()
                        .HasForeignKey("UsuarioValidadorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Expediente");

                    b.Navigation("ExpedienteLegal");

                    b.Navigation("UsuarioAdjunto");

                    b.Navigation("UsuarioValidador");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Expediente", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Bandeja", "BandejaActual")
                        .WithMany()
                        .HasForeignKey("BandejaActualID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioAdmision")
                        .WithMany()
                        .HasForeignKey("UsuarioAdmisionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioCreador")
                        .WithMany()
                        .HasForeignKey("UsuarioCreadorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BandejaActual");

                    b.Navigation("UsuarioAdmision");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.ExpedienteLegal", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithOne()
                        .HasForeignKey("SisMortuorio.Data.Entities.ExpedienteLegal", "ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Expediente", null)
                        .WithOne("ExpedienteLegal")
                        .HasForeignKey("SisMortuorio.Data.Entities.ExpedienteLegal", "ExpedienteID1");

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "JefeGuardia")
                        .WithMany()
                        .HasForeignKey("JefeGuardiaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioActualizacion")
                        .WithMany()
                        .HasForeignKey("UsuarioActualizacionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioAdmision")
                        .WithMany()
                        .HasForeignKey("UsuarioAdmisionID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioRegistro")
                        .WithMany()
                        .HasForeignKey("UsuarioRegistroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("JefeGuardia");

                    b.Navigation("UsuarioActualizacion");

                    b.Navigation("UsuarioAdmision");

                    b.Navigation("UsuarioRegistro");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Pertenencia", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany("Pertenencias")
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.SalidaMortuorio", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.ActaRetiro", "ActaRetiro")
                        .WithOne("SalidaMortuorio")
                        .HasForeignKey("SisMortuorio.Data.Entities.SalidaMortuorio", "ActaRetiroID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Bandeja", "BandejaLiberada")
                        .WithMany()
                        .HasForeignKey("BandejaLiberadaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Expediente", null)
                        .WithOne("SalidaMortuorio")
                        .HasForeignKey("SisMortuorio.Data.Entities.SalidaMortuorio", "ExpedienteID1");

                    b.HasOne("SisMortuorio.Data.Entities.ExpedienteLegal", "ExpedienteLegal")
                        .WithMany()
                        .HasForeignKey("ExpedienteLegalID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActaRetiro");

                    b.Navigation("BandejaLiberada");

                    b.Navigation("Expediente");

                    b.Navigation("ExpedienteLegal");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.SolicitudCorreccionExpediente", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithMany()
                        .HasForeignKey("ExpedienteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioResponsable")
                        .WithMany()
                        .HasForeignKey("UsuarioResponsableID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "UsuarioSolicita")
                        .WithMany()
                        .HasForeignKey("UsuarioSolicitaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expediente");

                    b.Navigation("UsuarioResponsable");

                    b.Navigation("UsuarioSolicita");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Usuario", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.VerificacionMortuorio", b =>
                {
                    b.HasOne("SisMortuorio.Data.Entities.Bandeja", "BandejaAsignada")
                        .WithMany()
                        .HasForeignKey("BandejaAsignadaID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SisMortuorio.Data.Entities.Expediente", "Expediente")
                        .WithOne("VerificacionMortuorio")
                        .HasForeignKey("SisMortuorio.Data.Entities.VerificacionMortuorio", "ExpedienteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "TecnicoAmbulancia")
                        .WithMany()
                        .HasForeignKey("TecnicoAmbulanciaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SisMortuorio.Data.Entities.Usuario", "Vigilante")
                        .WithMany()
                        .HasForeignKey("VigilanteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BandejaAsignada");

                    b.Navigation("Expediente");

                    b.Navigation("TecnicoAmbulancia");

                    b.Navigation("Vigilante");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.ActaRetiro", b =>
                {
                    b.Navigation("SalidaMortuorio");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Bandeja", b =>
                {
                    b.Navigation("Historial");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Expediente", b =>
                {
                    b.Navigation("ActaRetiro");

                    b.Navigation("AutoridadesExternas");

                    b.Navigation("CustodiaTransferencias");

                    b.Navigation("DeudaEconomica");

                    b.Navigation("DeudaSangre");

                    b.Navigation("Documentos");

                    b.Navigation("DocumentosLegales");

                    b.Navigation("ExpedienteLegal");

                    b.Navigation("HistorialBandejas");

                    b.Navigation("Pertenencias");

                    b.Navigation("SalidaMortuorio");

                    b.Navigation("VerificacionMortuorio");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.ExpedienteLegal", b =>
                {
                    b.Navigation("Autoridades");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("SisMortuorio.Data.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
